source "https://rubygems.org"
ruby "2.5.0"

gem "redcarpet"
gem "middleman"
gem "middleman-blog"
gem "middleman-syntax"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-autoprefixer"
gem "middleman-sprockets"
