source "https://rubygems.org"
ruby "2.3.0"

gem "redcarpet"
gem "middleman", ">= 4.0.0"
gem "middleman-blog"
gem "middleman-deploy", github: "middleman-contrib/middleman-deploy", branch: "master"
gem "middleman-syntax"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-autoprefixer"
